### PR TITLE
Hhinstalments

### PR DESCRIPTION
**Pull request by d97hah**

### CODE REVIEW

**Comment by xrotwang** [comment]
@d97hah did you manage to run this with the full data locally? Otherwise I could load the full data on the server, too. Would take about 3 hours, I guess, during which Glottolog may be a bit slower.

**Comment by d97hah** [comment]
Yes I tried and initializedb.py took 1h to go thru the tqdm loop over the
bibentries and about 7h (!) to flush thru the database. I recalled that
this last duration is highly dependent on the amount of free disk space to
use for postgres to flush or sthng, so Ill free up some when I try next.
Once in the db, searches in the clld app were "snappy" exactly like you
said. For development I play with a 1000 item subset.

Pada tanggal Sen, 10 Jan 2022 pukul 15.44 Robert Forkel <
***@***.***> menulis:

**Comment by xrotwang** [comment]
Ah, ok. So you created the DB before I factored out loading the text data. This is now done via
```
gramfinder index development.ini PATH/TO/WHERE/PTX*IS
```
which [flushes every 10 documents](https://github.com/clld/gramfinder/blob/main/gramfinder/commands/index.py#L80), and runs these batches in transactions. So it can be stopped and resumed without corrupting db state.

Maybe I'll run `gramfinder index`on the server tonight :)

**Comment by d97hah** [comment]
Probably. Noone told me I should run "gramfinder index" so I ran "clld
initdb development.ini" (actually I was at python
gramfinder/scripts/initializedb.py from 5 years ago :-) and refilled it
from the code in the branch you linked to. I didn't ask as you were on
holidays :-). Anyway, what should I actually run/edit?

Pada tanggal Sen, 10 Jan 2022 pukul 17.48 Robert Forkel <
***@***.***> menulis:

**Comment by xrotwang** [comment]
```
clld initdb development.ini
```
should now just load the reference data from Glottolog's `hh.bib`, and
```
gramfinder index development.ini PATH/TO/WHERE/txt*/IS
```
will load the the text data.

**Review by xrotwang — APPROVED** [review]

**Pull request merged**
